small changes in config to test admin regiser frontend
navikt/hm-grunndata-register pull request #1
Opened 2023-08-24 19:34 UTC by arshadkamran

2023-08-25 06:30 UTC, tuantrannav requested changes

2023-08-25 06:30 UTC, tuantrannav commented on src/main/resources/application.yml
> +            - http://localhost:3000
hei det er best å kjøre register/admin appen i samme ingress altså slikt finnhjelpemidler.intern.dev.nav.no/adminregister

2023-08-25 06:30 UTC, tuantrannav commented on .nais/nais.yml
> +        - application: hm-adminregister-frontend
det er ikke nøvendig, grunndata-register svarer direkte til brukeren, så den vil ikke via hm-adminregister-frontend

2023-08-25 06:39 UTC, arshadkamran commented on src/main/resources/application.yml
> +            - http://localhost:3000
Hei, det har jeg forsøkt uten lykke, men kan prøve igjen til uken i samarbeid med deg. Per nå vil disse endringer hjelpe å gå videre i utviklingen av frontend

2023-08-25 06:40 UTC, arshadkamran commented on .nais/nais.yml
> +        - application: hm-adminregister-frontend
Dette blir optimalisert til uken i samarbeid med deg. Nå vil jeg gjøre de endringene som kan få meg å komme videre

2023-08-28 10:12 UTC, arshadkamran commented
Det ser ut å fungere etter at ingress  finnhjelpemidler.intern.dev.nav.no/adminregister ble satt for frontend applikasjonen. Mest sannsynlig trenger man ikke disse endringer lenger.

2023-08-28 10:12 UTC, closed without merging